# Generated by Django 6.0.2 on 2026-02-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Choices', '0001_initial'),
        ('Experiences', '0002_remove_experience_map_link_and_more'),
        ('Profile', '0002_remove_guide_map_link_remove_guide_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
