# Generated by Django 6.0.2 on 2026-02-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Choices', '0002_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
