# Generated by Django 6.0.2 on 2026-03-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Choices', '0003_alter_language_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='mobileprovider',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='payoutstatus',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='travelpreference',
            options={'ordering': ['id']},
        ),
    ]
