# Generated by Django 6.0.2 on 2026-02-17 11:13

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Choices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('capacity', models.PositiveIntegerField()),
                ('remaining_slots', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Experience Title', max_length=100)),
                ('description', models.TextField(default='Experience Description', max_length=1000)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expertise', models.ManyToManyField(blank=True, to='Choices.travelpreference')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
