# Generated by Django 6.0.2 on 2026-02-08 10:00

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Choices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Experience Title', max_length=100)),
                ('description', models.TextField(default='Experience Description', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('map_link', models.URLField(default='https://www.google.com/maps/place/Kigali,+Rwanda/@-1.9705796,30.0644358,11z')),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), blank=True, default=list)),
                ('expertise', models.ManyToManyField(blank=True, to='Choices.travelpreference')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_experiences', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, to='Choices.language')),
                ('location', models.ManyToManyField(blank=True, to='Choices.location')),
                ('payment_methods', models.ManyToManyField(blank=True, to='Choices.paymentmethod')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
