# Generated by Django 6.0.2 on 2026-02-17 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Choices', '0001_initial'),
        ('Experiences', '0001_initial'),
        ('Location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Choices.language'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_location', to='Location.geolocation'),
        ),
        migrations.AddField(
            model_name='experience',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='Choices.paymentmethod'),
        ),
        migrations.AddField(
            model_name='experienceslot',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Experiences.experience'),
        ),
        migrations.AddIndex(
            model_name='experienceslot',
            index=models.Index(fields=['date'], name='Experiences_date_8224fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='experienceslot',
            unique_together={('experience', 'date')},
        ),
    ]
