# Generated by Django 6.0.2 on 2026-02-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experiences', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='map_link',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location',
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_location', to='Location.geolocation'),
        ),
    ]
