# Generated by Django 6.0.2 on 2026-02-17 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experiences', '0002_initial'),
        ('Location', '0002_remove_geolocation_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='experience',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='Location.geolocation'),
        ),
        migrations.AddIndex(
            model_name='experienceslot',
            index=models.Index(fields=['is_active', 'date'], name='Experiences_is_acti_76b966_idx'),
        ),
    ]
