# Generated by Django 6.0.2 on 2026-02-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experiences', '0003_alter_experience_options_experience_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceslot',
            name='end_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='experienceslot',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
