# Generated by Django 6.0.2 on 2026-03-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experiences', '0004_experienceslot_end_time_experienceslot_start_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experienceslot',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='experienceslot',
            constraint=models.UniqueConstraint(fields=('experience', 'date', 'start_time'), name='unique_experience_slot_start'),
        ),
    ]
