# Generated by Django 6.0.2 on 2026-03-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Choices', '0004_alter_language_options_alter_mobileprovider_options_and_more'),
        ('Experiences', '0006_experience_origin_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='origin_lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='Choices.language'),
        ),
    ]
