# Generated by Django 6.0.2 on 2026-04-04 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Experiences', '0007_alter_experience_origin_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceslot',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
