# Generated by Django 6.0.2 on 2026-02-17 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Choices', '0001_initial'),
        ('Payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payout',
            name='mobile_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='Choices.mobileprovider'),
        ),
        migrations.AddField(
            model_name='payout',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout_providers', to='Choices.mobileprovider'),
        ),
        migrations.AddField(
            model_name='payout',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Choices.payoutstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='payout',
            unique_together={('booking', 'provider_payout_id')},
        ),
    ]
