# Generated by Django 6.0.2 on 2026-02-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0001_initial'),
        ('Choices', '0001_initial'),
        ('Experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_bookings', to='Experiences.experience'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='Choices.bookingstatus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
