# Generated by Django 6.0.2 on 2026-02-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='address',
        ),
        migrations.AddField(
            model_name='geolocation',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='geolocation',
            name='place_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
