# Generated by Django 6.0.2 on 2026-02-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Experiences', '0003_alter_experience_options_experience_is_active_and_more'),
        ('Location', '0002_remove_geolocation_address_and_more'),
        ('Profile', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeoLocation',
            new_name='Location',
        ),
    ]
