# Generated by Django 6.0.2 on 2026-02-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_rename_geolocation_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='google_place_id',
            new_name='place_id',
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
