# Generated by Django 6.0.2 on 2026-02-08 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Choices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Guide Name', max_length=100)),
                ('bio', models.TextField(default='', max_length=1000)),
                ('map_link', models.URLField(default='https://www.google.com/maps/place/Kigali,+Rwanda/@-1.9705796,30.0644358,11z')),
                ('expertise', models.ManyToManyField(blank=True, to='Choices.travelpreference')),
                ('languages', models.ManyToManyField(blank=True, to='Choices.language')),
                ('location', models.ManyToManyField(blank=True, to='Choices.location')),
                ('payment_methods', models.ManyToManyField(blank=True, to='Choices.paymentmethod')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('languages', models.ManyToManyField(blank=True, to='Choices.language')),
                ('payment_methods', models.ManyToManyField(blank=True, to='Choices.paymentmethod')),
                ('travel_preferences', models.ManyToManyField(blank=True, to='Choices.travelpreference')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
