# Generated by Django 6.0.2 on 2026-02-17 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Choices', '0001_initial'),
        ('Location', '0001_initial'),
        ('Profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guide',
            name='expertise',
            field=models.ManyToManyField(blank=True, to='Choices.travelpreference'),
        ),
        migrations.AddField(
            model_name='guide',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Choices.language'),
        ),
        migrations.AddField(
            model_name='guide',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_location', to='Location.geolocation'),
        ),
        migrations.AddField(
            model_name='guide',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='Choices.paymentmethod'),
        ),
        migrations.AddField(
            model_name='guide',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourist',
            name='languages',
            field=models.ManyToManyField(blank=True, to='Choices.language'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='Choices.paymentmethod'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='travel_preferences',
            field=models.ManyToManyField(blank=True, to='Choices.travelpreference'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
