# Generated by Django 6.0.2 on 2026-03-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='name',
        ),
        migrations.AddField(
            model_name='guide',
            name='phone_number',
            field=models.IntegerField(default=780000002),
        ),
    ]
