# Generated by Django 6.0.2 on 2026-03-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_remove_guide_name_guide_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='phone_number',
            field=models.CharField(default='0780000002', max_length=10),
        ),
    ]
