# Generated by Django 6.0.2 on 2026-03-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Choices', '0004_alter_language_options_alter_mobileprovider_options_and_more'),
        ('Profile', '0004_alter_guide_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='payout_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_payout_provider', to='Choices.paymentmethod'),
        ),
    ]
