# Generated by Django 6.0.2 on 2026-03-10 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Choices', '0004_alter_language_options_alter_mobileprovider_options_and_more'),
        ('Profile', '0005_guide_payout_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='location',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='payment_methods',
        ),
        migrations.AlterField(
            model_name='guide',
            name='payout_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_payout_provider', to='Choices.mobileprovider'),
        ),
    ]
