# Generated by Django 6.0.2 on 2026-03-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemIndo',
            new_name='SystemInfo',
        ),
    ]
